/*
 * Automatically generated by xiqual-template.
 */

#include "xiqual.h"
#include "lui_button.h"
Â#inclue "lui_list.h"


static ulong running=1;


void realmain(Uint8 *keystate, SDLMod modstate,
	Uint8 mousestate, int mousex, int mousey)
{
	if(keystate[SDLK_ESCAPE]) running = 0;

	if(modstate) {
		printf("Modstate: 0x%x\n", modstate);
	}
}


int main(int argc, char *argv[])
{
	if(argc || argv) argc = 1;

