gcc -o new new.c -I/usr/local/include/xiqual -I/usr/include/SDL -D_REENTRANT -L/usr/local/lib -lxitools -llui -lSDL_ttf -lxitools -lxigfx -lSDL -lpthread -lSDL_image -lxitools  -I/usr/include/SDL -D_REENTRANT
-lSDL -lpthread -lSDL_mixer
