Import('env')
libxitools = env.Library('libxitools', Split("""
			file_getsize.c
			files.c
			opts.c

			idtostr.c
			iff_check.c
			iff_close.c
			iff_endchunk.c
			iff_fixsize.c
			iff_goodid.c
			iff_goodtype.c
			iff_new.c
			iff_newchunk.c
			iff_open.c
			iff_readchunkdata.c
			iff_readchunkheader.c
			iff_rewind.c
			iff_skipchunkdata.c
			iff_writechunkdata.c
			iff_correctchunk.c

			list_add.c
			list_delete.c
			list_free.c
			list_getnode.c
			list_insert.c
			list_new.c
			list_newitem.c
			list_remove.c
			list_makecircular.c
			list_addhead.c
			node_end.c
			node_makecircular.c
			node_start.c
			node_findbyname.c
			node_findbycontents.c

			cfg_freesection.c
			cfg_freevar.c
			cfg_loadprefs.c
			cfg_newsection.c
			cfg_newvar.c
			cfg_saveprefs.c
			cfg_mapfromenv.c
			cfg_isbool.c
			cfg_findsection.c
			cfg_findnext.c
			cfg_findvar.c

			xmlread.c
			xmlwrite.c
			xmlhooks.c
			xml_printesc.c
			
			strfind.c
			str_getvalue.c
			strlower.c
			strsplit.c
			strupper.c
			strisnum.c
			strtokenise.c
			ftr.c

			tag_alloclist.c
			tag_finditem.c
			tag_freelist.c
			tag_getdata.c
			tag_next.c

			mem_arrayget.c
			mem_arrayset.c

			crc32.c
			hash.c
			hash_newfromlist.c
			hash_merge.c
			"""))

env.Install('/usr/local/lib', libxitools)
